spring:
  application:
    name: eureka-provider  #服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka/ #服务中心地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 2004